import type { Model, NewsPost } from "./types";
import { goldenMockAssets } from "./mockAssets";

import m7 from "@/assets/model-07.jpg";
import m9 from "@/assets/model-09.jpg";
import m10 from "@/assets/model-10.jpg";
import m11 from "@/assets/model-11.jpg";
import m12 from "@/assets/model-12.jpg";
import m13 from "@/assets/model-13.jpg";
import hero from "@/assets/hero.jpg";

export const heroImage = hero;

export const seedModels: Model[] = [
  {
    slug: "chen-yu-xin",
    name: "Chen Yu-Xin",
    nameZh: "陳昱心",
    board: "women",
    gender: "women",
    languages: ["Mandarin", "Japanese", "English"],
    featured: true,
    city: "Taipei",
    cityZh: "台北",
    bioEn:
      "Taipei-born, Chen moved into fashion after three seasons of studio work and now splits her year between Taipei and Tokyo. Editorial, campaign and runway.",
    bioZh:
      "生於台北，在攝影棚工作三季後正式踏入時尚圈，目前往返台北與東京兩地。專長為雜誌、廣告與伸展台。",
    stats: {
      height: "178 cm",
      weight: "52 kg",
      bust: "82 cm",
      waist: "60 cm",
      hips: "88 cm",
      shoes: "EU 39",
      hair: "Dark brown",
      hairZh: "深棕",
      eyes: "Brown",
      eyesZh: "棕色",
    },
    portrait: goldenMockAssets.women.aya.portrait,
    hoverPortrait: goldenMockAssets.women.aya.hoverPortrait,
    gallery: [
      goldenMockAssets.women.aya.look02,
      goldenMockAssets.women.aya.look03,
      goldenMockAssets.women.aya.look04,
    ],
    digitals: [goldenMockAssets.women.aya.fullBody],
    tags: [
      "women",
      "taipei",
      "tokyo",
      "editorial-model",
      "fashion-model",
      "commercial-model",
      "print-model",
      "advertising-model",
      "runway",
    ],
  },
  {
    slug: "aoi-takahashi",
    name: "Aoi Takahashi",
    nameZh: "高橋葵",
    board: "women",
    gender: "women",
    languages: ["Japanese", "English"],
    featured: true,
    city: "Tokyo",
    cityZh: "東京",
    bioEn:
      "A short-cropped silhouette that has become a signature on Tokyo runways. Aoi works closely with independent designers and small-run labels.",
    bioZh: "俐落短髮的輪廓已成為東京伸展台上的標誌。葵長期與獨立設計師及小量品牌合作。",
    stats: {
      height: "175 cm",
      weight: "50 kg",
      bust: "80 cm",
      waist: "58 cm",
      hips: "86 cm",
      shoes: "EU 38",
      hair: "Black",
      hairZh: "黑色",
      eyes: "Dark brown",
      eyesZh: "深棕",
    },
    portrait: goldenMockAssets.women.mei.portrait,
    hoverPortrait: goldenMockAssets.women.mei.hoverPortrait,
    gallery: [goldenMockAssets.women.mei.fullBody, goldenMockAssets.women.mei.look03],
    digitals: [goldenMockAssets.women.mei.fullBody],
    tags: [
      "women",
      "tokyo",
      "beauty",
      "editorial-model",
      "fashion-model",
      "commercial-model",
      "print-model",
      "advertising-model",
      "runway",
    ],
  },
  {
    slug: "tanya-lim",
    name: "Tanya Lim",
    nameZh: "林丹雅",
    board: "women",
    gender: "women",
    languages: ["English", "Mandarin", "Malay"],
    featured: false,
    city: "Singapore",
    cityZh: "新加坡",
    bioEn:
      "Singapore-based with a long, quiet line that reads beautifully in motion. Regular face for regional beauty and swim campaigns.",
    bioZh: "以新加坡為據點，身形修長沉靜，動態表現尤其出色。經常出現於區域美妝與泳裝廣告。",
    stats: {
      height: "177 cm",
      weight: "51 kg",
      bust: "81 cm",
      waist: "59 cm",
      hips: "87 cm",
      shoes: "EU 39",
      hair: "Black",
      hairZh: "黑色",
      eyes: "Brown",
      eyesZh: "棕色",
    },
    portrait: goldenMockAssets.women.sora.portrait,
    hoverPortrait: goldenMockAssets.women.sora.hoverPortrait,
    gallery: [goldenMockAssets.women.sora.fullBody],
    digitals: [goldenMockAssets.women.sora.fullBody],
    tags: [
      "women",
      "asia",
      "beauty",
      "fashion-model",
      "commercial-model",
      "print-model",
      "advertising-model",
      "runway",
    ],
  },
  {
    slug: "lin-wei-jie",
    name: "Lin Wei-Jie",
    nameZh: "林威傑",
    board: "men",
    gender: "men",
    languages: ["Mandarin", "English"],
    featured: true,
    city: "Taipei",
    cityZh: "台北",
    bioEn:
      "Tailoring specialist with a still, unhurried presence in front of the camera. Six seasons of menswear across Taipei and Shanghai.",
    bioZh: "擅長西服類型，鏡頭前沉穩不躁。已累積台北與上海共六季男裝經驗。",
    stats: {
      height: "186 cm",
      weight: "73 kg",
      waist: "78 cm",
      shoes: "EU 43",
      hair: "Black",
      hairZh: "黑色",
      eyes: "Dark brown",
      eyesZh: "深棕",
    },
    portrait: goldenMockAssets.men.jun.portrait,
    hoverPortrait: goldenMockAssets.men.jun.hoverPortrait,
    gallery: [goldenMockAssets.men.jun.fullBody],
    digitals: [goldenMockAssets.men.jun.fullBody],
    tags: [
      "men",
      "taipei",
      "commercial-model",
      "fashion-model",
      "print-model",
      "advertising-model",
      "runway",
    ],
  },
  {
    slug: "han-min-jae",
    name: "Han Min-jae",
    nameZh: "韓敏宰",
    board: "men",
    gender: "men",
    languages: ["Korean", "English"],
    featured: false,
    city: "Seoul",
    cityZh: "首爾",
    bioEn:
      "Seoul-based, with a softer, longer-haired register that suits contemporary and streetwear casting.",
    bioZh: "以首爾為據點，中長髮的柔和氣質適合當代服飾與街頭風格選角。",
    stats: {
      height: "184 cm",
      weight: "70 kg",
      waist: "76 cm",
      shoes: "EU 42",
      hair: "Black",
      hairZh: "黑色",
      eyes: "Brown",
      eyesZh: "棕色",
    },
    portrait: goldenMockAssets.men.ren.portrait,
    hoverPortrait: goldenMockAssets.men.ren.hoverPortrait,
    gallery: [goldenMockAssets.men.ren.fullBody],
    digitals: [goldenMockAssets.men.ren.fullBody],
    tags: [
      "men",
      "seoul",
      "asia",
      "commercial-model",
      "fashion-model",
      "print-model",
      "advertising-model",
      "runway",
    ],
  },
  {
    slug: "hina-chinen",
    name: "Hina Chinen",
    nameZh: "知念陽菜",
    board: "new-faces",
    gender: "women",
    languages: ["Japanese", "English"],
    featured: true,
    city: "Okinawa",
    cityZh: "沖繩",
    bioEn:
      "Signed this season. Freckled, bare-faced and completely new to the industry — first tests shot in March.",
    bioZh: "本季新簽約。雀斑素顏、初入業界，三月完成首次試拍。",
    stats: {
      height: "174 cm",
      weight: "49 kg",
      bust: "79 cm",
      waist: "58 cm",
      hips: "85 cm",
      shoes: "EU 38",
      hair: "Dark brown",
      hairZh: "深棕",
      eyes: "Brown",
      eyesZh: "棕色",
    },
    portrait: goldenMockAssets.newFaces.nari,
    hoverPortrait: goldenMockAssets.newFaces.nariHover,
    gallery: [goldenMockAssets.newFaces.nari, goldenMockAssets.newFaces.nariHover],
    digitals: [goldenMockAssets.newFaces.nari],
    tags: ["new-faces", "natural-test", "scouting", "asia", "print-model", "beauty"],
  },
  {
    slug: "yang-shu-fen",
    name: "Yang Shu-Fen",
    nameZh: "楊淑芬",
    board: "talent",
    gender: "women",
    languages: ["Mandarin", "English"],
    featured: false,
    city: "Taipei",
    cityZh: "台北",
    bioEn:
      "Actor and presenter represented for commercial, film and brand ambassadorship work across Traditional Chinese speaking markets.",
    bioZh: "演員與主持人，代理商業廣告、影視及繁體中文市場的品牌代言合作。",
    stats: {
      height: "170 cm",
      weight: "53 kg",
      bust: "84 cm",
      waist: "63 cm",
      hips: "90 cm",
      shoes: "EU 38",
      hair: "Black",
      hairZh: "黑色",
      eyes: "Dark brown",
      eyesZh: "深棕",
    },
    portrait: m7,
    hoverPortrait: goldenMockAssets.hoverPairs.yangShuFen,
    gallery: [m7, goldenMockAssets.hoverPairs.yangShuFen],
    digitals: [m7],
    tags: [
      "actor",
      "host",
      "show-girl",
      "influencer",
      "kol",
      "taipei",
      "commercial-model",
      "advertising-model",
    ],
  },
  {
    slug: "kim-do-yun",
    name: "Kim Do-yun",
    nameZh: "金度允",
    board: "new-faces",
    gender: "men",
    languages: ["Korean", "English"],
    featured: false,
    city: "Busan",
    cityZh: "釜山",
    bioEn:
      "Scouted in Busan at eighteen and signed in April. Clean, unworked features and a natural ease in tailoring — first tests already circulating with Seoul casting.",
    bioZh:
      "十八歲於釜山被發掘，四月簽約。五官乾淨未經雕琢，穿著西服自然從容，首次試拍已在首爾選角圈流傳。",
    stats: {
      height: "183 cm",
      weight: "68 kg",
      waist: "74 cm",
      shoes: "EU 42",
      hair: "Black",
      hairZh: "黑色",
      eyes: "Dark brown",
      eyesZh: "深棕",
    },
    portrait: goldenMockAssets.newFaces.dai,
    hoverPortrait: goldenMockAssets.newFaces.daiHover,
    gallery: [goldenMockAssets.newFaces.dai, goldenMockAssets.newFaces.daiHover],
    digitals: [goldenMockAssets.newFaces.dai],
    tags: ["new-faces", "natural-test", "scouting", "seoul", "asia", "men", "print-model"],
  },
  {
    slug: "ravi-iskandar",
    name: "Ravi Iskandar",
    nameZh: "拉維・伊斯坎達爾",
    board: "talent",
    gender: "men",
    languages: ["English", "Malay", "Japanese"],
    featured: false,
    city: "Kuala Lumpur",
    cityZh: "吉隆坡",
    bioEn:
      "Actor and television presenter working across Malaysia, Singapore and Japan. Represented for drama, commercial and hosting work, in English, Malay and Japanese.",
    bioZh:
      "演員與電視主持人，工作橫跨馬來西亞、新加坡與日本。代理戲劇、商業廣告及主持工作，能以英語、馬來語與日語進行。",
    stats: {
      height: "181 cm",
      weight: "71 kg",
      waist: "80 cm",
      shoes: "EU 43",
      hair: "Black",
      hairZh: "黑色",
      eyes: "Dark brown",
      eyesZh: "深棕",
    },
    portrait: m9,
    hoverPortrait: goldenMockAssets.hoverPairs.raviIskandar,
    gallery: [m9, goldenMockAssets.hoverPairs.raviIskandar],
    digitals: [m9],
    tags: [
      "actor",
      "host",
      "show-girl",
      "influencer",
      "kol",
      "asia",
      "commercial-model",
      "advertising-model",
    ],
  },
  {
    slug: "amara-okonkwo",
    name: "Amara Okonkwo",
    nameZh: "阿瑪拉・奧孔科沃",
    board: "women",
    gender: "women",
    languages: ["English", "Mandarin"],
    featured: true,
    city: "Lagos / Taipei",
    cityZh: "拉哥斯／台北",
    bioEn:
      "Lagos-born and now based in Taipei, Amara moves between West African and East Asian markets. Runway, beauty and campaign, with a strong motion reel.",
    bioZh: "生於拉哥斯，現居台北，工作橫跨西非與東亞市場。專長伸展台、美妝與廣告，動態表現尤佳。",
    stats: {
      height: "179 cm",
      weight: "57 kg",
      bust: "83 cm",
      waist: "61 cm",
      hips: "89 cm",
      shoes: "EU 40",
      hair: "Black, natural",
      hairZh: "黑色自然捲",
      eyes: "Dark brown",
      eyesZh: "深棕",
    },
    portrait: m10,
    hoverPortrait: goldenMockAssets.hoverPairs.amaraOkonkwo,
    gallery: [m10, goldenMockAssets.hoverPairs.amaraOkonkwo],
    digitals: [m10],
    tags: [
      "women",
      "taipei",
      "beauty",
      "fashion-model",
      "commercial-model",
      "print-model",
      "advertising-model",
      "runway",
    ],
    videos: [
      {
        id: "amara-reel",
        source: "youtube",
        src: "aqz-KE-bpKQ",
        titleEn: "Showreel — spring campaign",
        titleZh: "動態作品集 — 春季廣告",
      },
    ],
  },
  {
    slug: "priya-raghunathan",
    name: "Priya Raghunathan",
    nameZh: "普里雅・拉古納坦",
    board: "women",
    gender: "women",
    languages: ["English", "Hindi", "Tamil"],
    featured: false,
    city: "Mumbai / Singapore",
    cityZh: "孟買／新加坡",
    bioEn:
      "Working across South and Southeast Asia, Priya is a regular face for jewellery, couture and hair campaigns in Mumbai, Singapore and Dubai.",
    bioZh: "工作範圍涵蓋南亞與東南亞，經常出現於孟買、新加坡與杜拜的珠寶、高級訂製服與髮妝廣告。",
    stats: {
      height: "176 cm",
      weight: "54 kg",
      bust: "82 cm",
      waist: "60 cm",
      hips: "88 cm",
      shoes: "EU 39",
      hair: "Black",
      hairZh: "黑色",
      eyes: "Dark brown",
      eyesZh: "深棕",
    },
    portrait: m11,
    hoverPortrait: goldenMockAssets.hoverPairs.priyaRaghunathan,
    gallery: [m11, goldenMockAssets.hoverPairs.priyaRaghunathan],
    digitals: [m11],
    tags: [
      "women",
      "asia",
      "beauty",
      "fashion-model",
      "commercial-model",
      "print-model",
      "advertising-model",
      "runway",
    ],
  },
  {
    slug: "noah-castellanos",
    name: "Noah Castellanos",
    nameZh: "諾亞・卡斯特拉諾斯",
    board: "men",
    gender: "men",
    languages: ["English", "Filipino", "Spanish", "Japanese"],
    featured: true,
    city: "Manila / Tokyo",
    cityZh: "馬尼拉／東京",
    bioEn:
      "Filipino-Spanish, raised in Manila and now shooting mostly out of Tokyo. Tailoring, sportswear and commercial film.",
    bioZh:
      "菲律賓與西班牙混血，於馬尼拉成長，目前主要以東京為工作據點。專長西服、運動服飾與商業影片。",
    stats: {
      height: "185 cm",
      weight: "72 kg",
      waist: "77 cm",
      shoes: "EU 43",
      hair: "Dark brown, curly",
      hairZh: "深棕捲髮",
      eyes: "Green",
      eyesZh: "綠色",
    },
    portrait: m12,
    hoverPortrait: goldenMockAssets.hoverPairs.noahCastellanos,
    gallery: [m12, goldenMockAssets.hoverPairs.noahCastellanos],
    digitals: [m12],
    tags: [
      "men",
      "tokyo",
      "asia",
      "commercial-model",
      "fashion-model",
      "print-model",
      "advertising-model",
      "runway",
    ],
    videos: [
      {
        id: "noah-motion",
        source: "youtube",
        src: "aqz-KE-bpKQ",
        titleEn: "Motion test — Tokyo studio",
        titleZh: "動態試拍 — 東京攝影棚",
      },
    ],
  },
  {
    slug: "margit-lindqvist",
    name: "Margit Lindqvist",
    nameZh: "瑪吉特・林德奎斯特",
    board: "talent",
    gender: "women",
    languages: ["Swedish", "English", "Mandarin"],
    featured: true,
    city: "Stockholm / Taipei",
    cityZh: "斯德哥爾摩／台北",
    bioEn:
      "Sixty-four and still working. Margit represents our classic division — luxury, skincare and lifestyle campaigns that want a real face and a real history.",
    bioZh:
      "六十四歲，仍在線上。瑪吉特代表我們的經典分類，適合追求真實面孔與歲月質地的精品、保養與生活風格廣告。",
    stats: {
      height: "172 cm",
      weight: "59 kg",
      bust: "88 cm",
      waist: "68 cm",
      hips: "94 cm",
      shoes: "EU 39",
      hair: "Silver",
      hairZh: "銀白",
      eyes: "Blue",
      eyesZh: "藍色",
    },
    portrait: m13,
    hoverPortrait: goldenMockAssets.hoverPairs.margitLindqvist,
    gallery: [m13, goldenMockAssets.hoverPairs.margitLindqvist],
    digitals: [m13],
    tags: [
      "actor",
      "host",
      "beauty",
      "commercial-model",
      "advertising-model",
      "influencer",
      "kol",
      "asia",
    ],
  },
];

export const seedNews: NewsPost[] = [
  {
    slug: "spring-board-update",
    date: "2026-07-14",
    titleEn: "Spring board update",
    titleZh: "春季分類更新",
    excerptEn: "Four new signings join the Women and New Faces boards ahead of the Taipei season.",
    excerptZh: "台北時裝季前夕，四位新簽約模特兒加入女模與新面孔分類。",
    bodyEn: [
      "Ahead of the Taipei season we have added four new faces across the Women and New Faces boards, each scouted in the last six months across Taiwan, Japan and Singapore.",
      "Digitals and full portfolios are available on request. Booking enquiries should be directed to the Taipei desk.",
    ],
    bodyZh: [
      "在台北時裝季開始之前，我們於女模與新面孔分類新增四位面孔，皆為近半年間於台灣、日本與新加坡發掘。",
      "生活照與完整作品集可另行索取，工作邀約請聯繫台北辦公室。",
    ],
    cover: goldenMockAssets.news.springBoardUpdate,
    tags: ["women", "new-faces", "taipei", "fashion-model", "scouting", "runway"],
    videos: [
      {
        id: "spring-board-clip",
        source: "youtube",
        src: "aqz-KE-bpKQ",
        titleEn: "Meet the new signings",
        titleZh: "認識新簽約模特兒",
      },
    ],
  },
  {
    slug: "tokyo-showroom",
    date: "2026-06-02",
    titleEn: "Tokyo showroom, June",
    titleZh: "六月東京展間",
    excerptEn:
      "A three-day showroom in Shibuya for casting directors and stylists working the autumn calendar.",
    excerptZh: "於澀谷舉辦為期三天的展間，面向秋季檔期的選角與造型團隊。",
    bodyEn: [
      "We hosted a three-day showroom in Shibuya for casting directors and stylists preparing the autumn calendar, with fourteen models present across two boards.",
      "Thank you to everyone who came through. The next showroom will be announced in September.",
    ],
    bodyZh: [
      "我們於澀谷舉辦三天展間，接待籌備秋季檔期的選角與造型團隊，共十四位模特兒到場，橫跨兩個分類。",
      "感謝所有到訪的夥伴，下一場展間將於九月公布。",
    ],
    cover: goldenMockAssets.news.tokyoShowroom,
    tags: [
      "tokyo",
      "editorial-model",
      "fashion-model",
      "commercial-model",
      "advertising-model",
      "print-model",
      "runway",
    ],
  },
  {
    slug: "on-scouting-in-asia",
    date: "2026-04-21",
    titleEn: "On scouting in Asia",
    titleZh: "關於亞洲的星探工作",
    excerptEn:
      "Why we look outside the capitals, and what we actually want to see in an application.",
    excerptZh: "為什麼我們走出首都城市，以及一份申請中我們真正想看到的東西。",
    bodyEn: [
      "Most of our recent signings did not come from Taipei, Tokyo or Seoul. They came from Tainan, Okinawa and Johor — places where nobody is looking.",
      "What we want in an application is simple: daylight, no retouching, no filter, and a plain background. Face, full body, profile. That is enough.",
    ],
    bodyZh: [
      "我們近期簽下的模特兒多數並非來自台北、東京或首爾，而是台南、沖繩與柔佛——那些沒有人在尋找的地方。",
      "我們希望在申請中看到的很簡單：日光、不修圖、不加濾鏡、素色背景。臉部、全身、側面，這樣就足夠了。",
    ],
    cover: goldenMockAssets.news.scoutingInAsia,
    tags: ["scouting", "asia", "new-faces", "natural-test", "beauty", "print-model"],
  },
];
