/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ScoutedRouteImport } from './routes/scouted'
import { Route as KeywordsSlugRouteImport } from './routes/keywords.$slug'
import { Route as NewsIndexRouteImport } from './routes/news.index'
import { Route as NewsSlugRouteImport } from './routes/news.$slug'
import { Route as ModelsBoardIndexRouteImport } from './routes/models.$board.index'
import { Route as ModelsBoardSlugRouteImport } from './routes/models.$board.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoutedRoute = ScoutedRouteImport.update({
  id: '/scouted',
  path: '/scouted',
  getParentRoute: () => rootRouteImport,
} as any)
const KeywordsSlugRoute = KeywordsSlugRouteImport.update({
  id: '/keywords/$slug',
  path: '/keywords/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsIndexRoute = NewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsSlugRoute = NewsSlugRouteImport.update({
  id: '/news/$slug',
  path: '/news/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsBoardIndexRoute = ModelsBoardIndexRouteImport.update({
  id: '/models/$board/',
  path: '/models/$board/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsBoardSlugRoute = ModelsBoardSlugRouteImport.update({
  id: '/models/$board/$slug',
  path: '/models/$board/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/scouted': typeof ScoutedRoute
  '/keywords/$slug': typeof KeywordsSlugRoute
  '/news/$slug': typeof NewsSlugRoute
  '/news/': typeof NewsIndexRoute
  '/models/$board/$slug': typeof ModelsBoardSlugRoute
  '/models/$board/': typeof ModelsBoardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/scouted': typeof ScoutedRoute
  '/keywords/$slug': typeof KeywordsSlugRoute
  '/news/$slug': typeof NewsSlugRoute
  '/news': typeof NewsIndexRoute
  '/models/$board/$slug': typeof ModelsBoardSlugRoute
  '/models/$board': typeof ModelsBoardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/scouted': typeof ScoutedRoute
  '/keywords/$slug': typeof KeywordsSlugRoute
  '/news/$slug': typeof NewsSlugRoute
  '/news/': typeof NewsIndexRoute
  '/models/$board/$slug': typeof ModelsBoardSlugRoute
  '/models/$board/': typeof ModelsBoardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/about'
    | '/admin'
    | '/contact'
    | '/scouted'
    | '/keywords/$slug'
    | '/news/$slug'
    | '/news/'
    | '/models/$board/$slug'
    | '/models/$board/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$slug'
    | '/about'
    | '/admin'
    | '/contact'
    | '/scouted'
    | '/keywords/$slug'
    | '/news/$slug'
    | '/news'
    | '/models/$board/$slug'
    | '/models/$board'
  id:
    | '__root__'
    | '/'
    | '/$slug'
    | '/about'
    | '/admin'
    | '/contact'
    | '/scouted'
    | '/keywords/$slug'
    | '/news/$slug'
    | '/news/'
    | '/models/$board/$slug'
    | '/models/$board/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugRoute: typeof SlugRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  ContactRoute: typeof ContactRoute
  ScoutedRoute: typeof ScoutedRoute
  KeywordsSlugRoute: typeof KeywordsSlugRoute
  NewsSlugRoute: typeof NewsSlugRoute
  NewsIndexRoute: typeof NewsIndexRoute
  ModelsBoardSlugRoute: typeof ModelsBoardSlugRoute
  ModelsBoardIndexRoute: typeof ModelsBoardIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scouted': {
      id: '/scouted'
      path: '/scouted'
      fullPath: '/scouted'
      preLoaderRoute: typeof ScoutedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/keywords/$slug': {
      id: '/keywords/$slug'
      path: '/keywords/$slug'
      fullPath: '/keywords/$slug'
      preLoaderRoute: typeof KeywordsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/': {
      id: '/news/'
      path: '/news'
      fullPath: '/news/'
      preLoaderRoute: typeof NewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/$slug': {
      id: '/news/$slug'
      path: '/news/$slug'
      fullPath: '/news/$slug'
      preLoaderRoute: typeof NewsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models/$board/': {
      id: '/models/$board/'
      path: '/models/$board'
      fullPath: '/models/$board/'
      preLoaderRoute: typeof ModelsBoardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models/$board/$slug': {
      id: '/models/$board/$slug'
      path: '/models/$board/$slug'
      fullPath: '/models/$board/$slug'
      preLoaderRoute: typeof ModelsBoardSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugRoute: SlugRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  ContactRoute: ContactRoute,
  ScoutedRoute: ScoutedRoute,
  KeywordsSlugRoute: KeywordsSlugRoute,
  NewsSlugRoute: NewsSlugRoute,
  NewsIndexRoute: NewsIndexRoute,
  ModelsBoardSlugRoute: ModelsBoardSlugRoute,
  ModelsBoardIndexRoute: ModelsBoardIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
